# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestAaaa():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit() 
  
  def test_aaaa(self):
    # Test name: aaaa
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("https://coinmarketcap.com/")
    # 2 | setWindowSize | 1665x1080 | 
    self.driver.set_window_size(1665, 1080)
    # 3 | click | css=tr:nth-child(3) .cmc-link .sc-aef7b723-0 > .sc-e225a64a-0 | 
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(3) .cmc-link .sc-aef7b723-0 > .sc-e225a64a-0").click()
    # 4 | mouseOver | css=.sc-7ed8b501-2:nth-child(1) .sc-a4a6801b-0 | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".sc-7ed8b501-2:nth-child(1) .sc-a4a6801b-0")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 5 | mouseOut | css=.sc-7ed8b501-2:nth-child(1) .sc-a4a6801b-0 | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
  
